---
sudo: true

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop

install: true
script:
  - scripts/docker-compose-lint.sh
  - mvn clean install
  - cd compose
  - docker network create back-end
  - docker volume create db
  - docker-compose build
  - docker-compose up -d
  - sleep 5s
  - curl -Is http://localhost/ | grep -q "^HTTP\/1\.1 200"

after_success:
  - pushd ..
  - bash <(curl -s https://codecov.io/bash)
  - popd

after_script:
  - docker-compose logs
  - docker-compose down

branches:
  only:
    - master
    - dev
