---
sudo: true
language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

before_install:
  - docker-compose up -d postgres

install: true
script:
  - mvn clean install

after_success:
  - docker-compose logs postgres
  - docker-compose down
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - dev
