---
sudo: true

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop

install: true
script: 
  - docker network create back-end
  - docker-compose -f docker-compose-immutable-psql.yml up -d
  - >-
    docker run
    --network back-end
    -it --rm
    -e DATABASE_URL=postgresql://postgres:5432/cruise_company
    -v "$HOME/.m2:/root/.m2"
    -v "$PWD":/usr/src/app
    -w /usr/src/app maven:3.5.2-jdk-8-alpine
    mvn clean install
  - docker-compose down
  - sudo chown -R $UID:$UID "$PWD/target"
  - docker volume create db
  - docker-compose build
  - docker-compose up -d
  - sleep 5s
  - curl -Is http://localhost/ | grep -q "^HTTP\/1\.1 200"

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - docker-compose logs
  - docker-compose down

branches:
  only:
    - master
    - dev
