FROM openjdk:8-jdk-alpine

ENV UID 1000
ENV GID 1000
ENV USER java
ENV GROUP java

RUN addgroup -g $GID $GROUP && adduser -D -G $GROUP -u $UID $USER 

ENV APP cruise-company
ENV VER 1.0-SNAPSHOT
ENV INSTALL /opt/$APP
ENV TARGET target
ENV WEBAPP src/main/webapp

COPY $TARGET $INSTALL/$TARGET
COPY $WEBAPP $INSTALL/$WEBAPP
RUN chown $USER:$GROUP -R $INSTALL

WORKDIR $INSTALL
USER $USER
EXPOSE 8080

ENTRYPOINT java -jar $TARGET/$APP-$VER.jar