---
version: "2.3"

services:

  postgres:
    extends:
      service: postgres
      file: docker-compose-common-psql.yml
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - back-end
    volumes:
      - ./db:/docker-entrypoint-initdb.d

networks:
  back-end:
    external: true
