---
version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB}
    ports:
      - 5432:5432
    networks:
      - back-end
    volumes:
      - db:/var/lib/postgresql/data
      - ${POSTGRES_INIT}:/docker-entrypoint-initdb.d

networks:
  back-end:
    external: true

volumes:
  db:
    external: true