---
version: "3"

services:

  db:
    container_name: db
    network_mode: host
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB}
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ${POSTGRES_INIT}:/docker-entrypoint-initdb.d
