---
version: "2.3"

services:

  postgres:
    extends:
      service: postgres
      file: docker-compose-common-psql.yml
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - back-end
    volumes:
      - db:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d

  webapp:
    container_name: webapp
    restart: always
    depends_on:
      - postgres
    image: webapp
    environment:
      DATABASE_URL: postgresql://postgres:5432/${POSTGRES_DB}
    build: ..
    ports:
      - ${HOST_WEB_PORT}:8080
    networks:
      - back-end

networks:
  back-end:
    external: true

volumes:
  db:
    external: true
